### ISSUE TITLE
.py file works fine but when compiled with py2app fails on rumps import

### ISSUE THREAD

**Issue by fredthedead** [jaredks/rumps#100]
When running from the .py file everything works fine.

After compiling with py2app the app crushes straight away with 'app Error' and the following error is printed in console:

```
littlefred:~ fred$ /Users/fred/proj/code/dist/app.app/Contents/MacOS/app ; exit;
Traceback (most recent call last):
  File "/Users/fred/proj/code/dist/app.app/Contents/Resources/__boot__.py", line 395, in <module>
    _run()
  File "/Users/fred/proj/code/dist/app.app/Contents/Resources/__boot__.py", line 370, in _run
    exec(compile(source, path, 'exec'), globals(), globals())
  File "/Users/fred/proj/code/dist/app.app/Contents/Resources/app.py", line 1, in <module>
    import rumps
  File "/Users/fred/proj/code/dist/app.app/Contents/Resources/lib/python2.7/rumps/__init__.py", line 25, in <module>
    from .rumps import (separator, debug_mode, alert, notification, application_support, timers, quit_application, timer,
  File "/Users/fred/proj/code/dist/app.app/Contents/Resources/lib/python2.7/rumps/rumps.py", line 15, in <module>
    from Foundation import (NSDate, NSTimer, NSRunLoop, NSDefaultRunLoopMode, NSSearchPathForDirectoriesInDomains,
  File "Foundation/__init__.pyc", line 8, in <module>
  File "objc/__init__.pyc", line 18, in <module>
  File "objc/__init__.pyc", line 15, in _update
AttributeError: 'module' object has no attribute '_objc'
```

**Comment by jaredks** [comment]
@fredthedead Can you provide your versions of python, macOS, and PyObjC? Possibly also would be helpful to get the minimal `setup.py` that causes this to happen.

**Comment by fredthedead** [comment]
Thanks I've resolved the issue. After changing the order of imports in my app.py file it threw a different error about not being able to find a module called `'_sysconfigdata'`. I've added that module to my `setup.py` file as an explicit package and it's working fine now...

My versions are: python 2.7 (Anaconda) and macOS 10.13.4
