### ISSUE TITLE
NameError: name 'basestring' is not defined - Python3.8

### ISSUE THREAD

**Issue by cavonlee** [jaredks/rumps#160]
Seems like dependency lib pilo is not available for Python 3
Code:
```python
import rump

class AwesomeStatusBarApp(rumps.App):
    @rumps.clicked("Preferences")
    def prefs(self, _):
        rumps.alert("jk! no preferences available!")

    @rumps.clicked("Silly button")
    def onoff(self, sender):
        sender.state = not sender.state

    @rumps.clicked("Say hi")
    def sayhi(self, _):
        rumps.notification("Awesome title", "amazing subtitle", "hi!!1")

if __name__ == "__main__":
    AwesomeStatusBarApp("Awesome App").run()
```
Output:
```bash
Traceback (most recent call last):
  File "test_rump.py", line 1, in <module>
    import rump
  File "/Users/cavon/Library/Python/3.8/lib/python/site-packages/rump/__init__.py", line 137, in <module>
    from . import exc
  File "/Users/cavon/Library/Python/3.8/lib/python/site-packages/rump/exc.py", line 1, in <module>
    import pilo
  File "/Users/cavon/Library/Python/3.8/lib/python/site-packages/pilo/__init__.py", line 105, in <module>
    from . import source
  File "/Users/cavon/Library/Python/3.8/lib/python/site-packages/pilo/source/__init__.py", line 209, in <module>
    class ParserMixin(object):
  File "/Users/cavon/Library/Python/3.8/lib/python/site-packages/pilo/source/__init__.py", line 266, in ParserMixin
    basestring: as_string,
NameError: name 'basestring' is not defined
```

**Comment by cavonlee** [comment]
Find out i import a library called "rump" not "rumps". It works now!
