### ISSUE TITLE
ImportError: cannot import name 'Mapping' from 'collections'

### ISSUE THREAD

**Issue by PyKoch** [jaredks/rumps#169]
I'm running the first example on [the documentation](https://rumps.readthedocs.io/en/latest/examples.html#simple-subclass-structure). The result is this error: 

```
Traceback (most recent call last):
  File "/Users/vk0604/essence/rumps_nmore/rumps_test.py", line 1, in <module>
    import rumps
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/rumps/__init__.py", line 25, in <module>
    from .rumps import (separator, debug_mode, alert, notification, application_support, timers, quit_application, timer,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/rumps/rumps.py", line 33, in <module>
    from collections import Mapping, Iterable
ImportError: cannot import name 'Mapping' from 'collections' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)
```
Python version 3.10.0
OSX 10.14.6

Does rumps.py need updating? [The issue seems to occur with various packages. ](https://stackoverflow.com/questions/69381312/in-vs-code-importerror-cannot-import-name-mapping-from-collections)

Any wisdom?

**Comment by PyKoch** [comment]
Replacing 
`from collections import Mapping, Iterable`
with 
`from collections.abc import Mapping, Iterable, MutableMapping`
in rumps.py did the trick.
