### ISSUE TITLE
ModuleNotFoundError: No module named 'imp'

### ISSUE THREAD

**Issue by esseti** [jaredks/rumps#219]
I've a piece of code that relies on rumps and it's built with app2py
https://github.com/esseti/vince

since i've changed the mac, now when building i discovered that the app does not start anymore, with this error. 
while if i run the code directly it works 

do you have any clue why this is happening?

i use python-3.11

```
/Users/stefano/sw/vince/src/dist/Vince2.app/Contents/Resources/__boot__.py:116: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
Traceback (most recent call last):
  File "/Users/stefano/sw/vince/src/dist/Vince2.app/Contents/Resources/__boot__.py", line 161, in <module>
    _run()
  File "/Users/stefano/sw/vince/src/dist/Vince2.app/Contents/Resources/__boot__.py", line 84, in _run
    exec(compile(source, path, "exec"), globals(), globals())
  File "/Users/stefano/sw/vince/src/dist/Vince2.app/Contents/Resources/vince.py", line 2, in <module>
    import rumps
  File "rumps/__init__.pyc", line 25, in <module>
  File "rumps/notifications.pyc", line 14, in <module>
  File "Foundation/__init__.pyc", line 203, in <module>
  File "Foundation/__init__.pyc", line 12, in _setup
  File "CoreFoundation/__init__.pyc", line 37, in <module>
  File "CoreFoundation/__init__.pyc", line 12, in _setup
  File "objc/__init__.pyc", line 7, in <module>
  File "objc/_objc.pyc", line 13, in <module>
  File "objc/_objc.pyc", line 2, in __load
ModuleNotFoundError: No module named 'imp'
```

**Comment by esseti** [comment]
You are right that works (I used --include)
